### ISSUE TITLE
-

### ISSUE THREAD

**Issue by lax2k3** [mwasikz/robo-cafe-rms#1]
Hello Sir,how to run the project?

**Comment by mwasikz** [comment]
[Follow this tutorial](https://www.youtube.com/watch?v=aAoGurfF-EY&ab_channel=GeekyScript)

**Comment by lax2k3** [comment]
Warning: include(../config/constants.php): Failed to open stream: No such file or directory in C:\xampp\htdocs\robo-cafe-rms-main\admin\index.php on line 1

Warning: include(): Failed opening '../config/constants.php' for inclusion (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\robo-cafe-rms-main\admin\index.php on line 1

Fatal error: Uncaught Error: Undefined constant "SITEURL" in C:\xampp\htdocs\robo-cafe-rms-main\admin\login-check.php:11 Stack trace: #0 C:\xampp\htdocs\robo-cafe-rms-main\admin\index.php(2): include() #1 {main} thrown in C:\xampp\htdocs\robo-cafe-rms-main\admin\login-check.php on line 11

Can you please tell me how to solve this error?

**Comment by mwasikz** [comment]
I have found the error and fixed it. You need to redownload all the files as I have made changes to a lot of them. Have you set up the database? If not then set up the database first. The database file can be found at "frontend/db/". 

Let me know if it works this time or not.

**Comment by lax2k3** [comment]
> I have found the error and fixed it. You need to redownload all the files as I have made changes to a lot of them. Have you set up the database? If not then set up the database first. The database file can be found at "frontend/db/".
> 
> Let me know if it works this time or not.

Yes Sir I already set up database I'll give a try

**Comment by lax2k3** [comment]
Sir the website is working fine but some Images are not getting loaded

**Comment by lax2k3** [comment]
**Helllo Sir I'm getting this Error**

Not Found
The requested URL was not found on this server.

Apache/2.4.56 (Win64) OpenSSL/1.1.1t PHP/8.2.4 Server at localhost Port 80

**Some Images and Logo is not getting loaded**

**Comment by mwasikz** [comment]
You need replace missing images with your own image.

**Comment by lax2k3** [comment]
Not Found
The requested URL was not found on this server.

Apache/2.4.56 (Win64) OpenSSL/1.1.1t PHP/8.2.4 Server at localhost Port 80

**How to fix this Error?**

**Comment by mwasikz** [comment]
Show me a screenshot with the URL.

**Comment by lax2k3** [comment]
<img width="504" alt="image" src="https://github.com/mwasikz/robo-cafe-rms/assets/92925532/f87fbb56-cb67-4425-b280-97b3b594db98">

<img width="480" alt="image" src="https://github.com/mwasikz/robo-cafe-rms/assets/92925532/6db12ef8-0efc-4bb0-a7cd-14a9ee11fc0e">


***Whenever I try to add admin or update items in Inventory its give me error***

![image](https://github.com/mwasikz/robo-cafe-rms/assets/92925532/9a993b64-146b-438d-b398-b1742bd5c17c)


**In admin panel Images are not getting loaded**

**Comment by mwasikz** [comment]
I have fixed the error. Redownload the project and try again.

**Comment by lax2k3** [comment]
**Thank you so much sir you are Amazing the website is working fine but still some images are not getting loaded**

**Comment by mwasikz** [comment]
Images should load now. Redownload the project.

**Comment by lax2k3** [comment]
**Thank you, sir. The website is working flawlessly. 
Sir, may I ask for a favor?
Could you please add an Indian payment gateway and a bill generating system, if you have the time?**

**Comment by mwasikz** [comment]
Implementing a whole new payment gateway to this project would take a lot of time and effort. I am sorry I can not do that. Please search on YouTube about how to implement payment gateway in PHP.

**Comment by lax2k3** [comment]
No problem, sir. Thank you so much for your efforts. You are a lifesaver.

**Comment by lax2k3** [comment]
![image](https://github.com/mwasikz/robo-cafe-rms/assets/92925532/9b2a05f4-94dc-4483-ac91-b8336968bab2)

**Sir when I tried to add new items it is showing failed to upload image**

**Comment by mwasikz** [comment]
Fixed. Redownload the "add-food.php" and "add-category.php" files.

**Comment by lax2k3** [comment]
![image](https://github.com/mwasikz/robo-cafe-rms/assets/92925532/f0e3a5a8-8fe4-4d39-9565-b69e6d184662)

<img width="713" alt="image" src="https://github.com/mwasikz/robo-cafe-rms/assets/92925532/518182d9-5c66-4121-b4ee-a830919dba2a">


**Now it is showing fail to remove and image is not loading in admin panel**

**Comment by mwasikz** [comment]
Fixed. Redownload "add-category.php", "add-food.php", "delete-category.php", "delete-food.php" files.

**Comment by lax2k3** [comment]
<img width="956" alt="image" src="https://github.com/mwasikz/robo-cafe-rms/assets/92925532/01ee0f06-0ca1-4779-8ace-0f794771d97c">

**Now Frontend image is not loading**

**Comment by mwasikz** [comment]
There was a problem with the image folder path. It's fixed now. Redownload the whole project and try again.

**Comment by lax2k3** [comment]
**Thank you sir all problems are solved👍**

**Comment by lax2k3** [comment]
<img width="280" alt="image" src="https://github.com/mwasikz/robo-cafe-rms/assets/92925532/ff007bc1-b7b7-4be1-b099-b0c4be04bdfd">


![image](https://github.com/mwasikz/robo-cafe-rms/assets/92925532/fe7cfd86-c4e1-4de3-80e3-40302a258a0b)


Sir I changed the logo but it is not reflecting 
In files it is showing but not showing on browser

**Comment by lax2k3** [comment]
![image](https://github.com/mwasikz/robo-cafe-rms/assets/92925532/51016e1e-d911-4e2e-b8ad-c2159259961c)

Sir this logo is not loading do you know where the path is?

**Comment by mwasikz** [comment]
Fixed. Redownload the "frontend/css/login-front.css" file.

**Comment by lax2k3** [comment]
> Fixed. Redownload the "frontend/css/login-front.css" file.

Thanx it worked
